version: "3.7"
services:
  web:
    image: simodalla/learndocker_ch11-web:2.0
    networks:
      - pets-net
    ports:
      - 3000:3000
    deploy:
      replicas: 3
    db:
      image: simodalla/learndocker_ch11-db:2.0
      networks:
        - pets-net
      volumes:
        - pets-data:/var/lib/postgresql/data
networks:
  pets-net:
