version: "2.4"
services:
  web:
    image: simodalla/learndocker_ch11-web:2.0
    build: web
    ports:
      - 3000:3000
  db:
    image: simodalla/learndocker_ch11-db:2.0
    build: database
    volumes:
      - pets-data:/var/lib/postgresql/data

volumes:
  pets-data: